name: education_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  chewie: ^1.7.4
  cloud_firestore: ^4.14.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  file_picker: ^6.1.1
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.6.0
  get_it: ^7.6.4
  iconly: ^1.0.1
  image_picker: ^1.0.5
  intl: ^0.19.0
  lottie: ^2.7.0
  open_file: ^3.3.2
  path_provider: ^2.1.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.5
  url_launcher: ^6.2.2
  video_thumbnail: ^0.5.3
  youtube_metadata: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.5
  mocktail: ^1.0.2
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - assets/vectors/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
